#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Dewolf.Model;

namespace Dewolf.Model	
{
	public partial class Autorizacao
	{
		private int _idautorizacao;
		public virtual int Idautorizacao
		{
			get
			{
				return this._idautorizacao;
			}
			set
			{
				this._idautorizacao = value;
			}
		}
		
		private string _nomeResponsavel;
		public virtual string NomeResponsavel
		{
			get
			{
				return this._nomeResponsavel;
			}
			set
			{
				this._nomeResponsavel = value;
			}
		}
		
		private DateTime _data;
		public virtual DateTime Data
		{
			get
			{
				return this._data;
			}
			set
			{
				this._data = value;
			}
		}
		
		private string _numDocResponsavel;
		public virtual string NumDocResponsavel
		{
			get
			{
				return this._numDocResponsavel;
			}
			set
			{
				this._numDocResponsavel = value;
			}
		}
		
		private string _telefoneContato;
		public virtual string TelefoneContato
		{
			get
			{
				return this._telefoneContato;
			}
			set
			{
				this._telefoneContato = value;
			}
		}
		
		private IList<Passageiro> _passageiros = new List<Passageiro>();
		public virtual IList<Passageiro> Passageiros
		{
			get
			{
				return this._passageiros;
			}
		}
		
	}
}
#pragma warning restore 1591
