#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Dewolf.Model;

namespace Dewolf.Model	
{
	public partial class DewolfModel : OpenAccessContext, IDewolfModelUnitOfWork
	{
		private static string connectionStringName = @"Connection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntitiesModel.rlinq");
		
		public DewolfModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public DewolfModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public DewolfModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public DewolfModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public DewolfModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Viagem> Viagems 
		{
			get
			{
				return this.GetAll<Viagem>();
			}
		}
		
		public IQueryable<Passagem> Passagems 
		{
			get
			{
				return this.GetAll<Passagem>();
			}
		}
		
		public IQueryable<Passageiro> Passageiros 
		{
			get
			{
				return this.GetAll<Passageiro>();
			}
		}
		
		public IQueryable<Autorizacao> Autorizacaos 
		{
			get
			{
				return this.GetAll<Autorizacao>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MySql";
			backend.ProviderName = "MySql.Data.MySqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of DewolfModel.
		/// </summary>
		/// <param name="config">The BackendConfiguration of DewolfModel.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IDewolfModelUnitOfWork : IUnitOfWork
	{
		IQueryable<Viagem> Viagems
		{
			get;
		}
		IQueryable<Passagem> Passagems
		{
			get;
		}
		IQueryable<Passageiro> Passageiros
		{
			get;
		}
		IQueryable<Autorizacao> Autorizacaos
		{
			get;
		}
	}
}
#pragma warning restore 1591
