#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Dewolf.Model;

namespace Dewolf.Model	
{
	public partial class Viagem
	{
		private int _idviagem;
		public virtual int Idviagem
		{
			get
			{
				return this._idviagem;
			}
			set
			{
				this._idviagem = value;
			}
		}
		
		private string _origem;
		public virtual string Origem
		{
			get
			{
				return this._origem;
			}
			set
			{
				this._origem = value;
			}
		}
		
		private string _destino;
		public virtual string Destino
		{
			get
			{
				return this._destino;
			}
			set
			{
				this._destino = value;
			}
		}
		
		private int _distancia;
		public virtual int Distancia
		{
			get
			{
				return this._distancia;
			}
			set
			{
				this._distancia = value;
			}
		}
		
		private DateTime _dataHorario;
		public virtual DateTime DataHorario
		{
			get
			{
				return this._dataHorario;
			}
			set
			{
				this._dataHorario = value;
			}
		}
		
		private string _motorista;
		public virtual string Motorista
		{
			get
			{
				return this._motorista;
			}
			set
			{
				this._motorista = value;
			}
		}
		
		private int _qtdePedagio;
		public virtual int QtdePedagio
		{
			get
			{
				return this._qtdePedagio;
			}
			set
			{
				this._qtdePedagio = value;
			}
		}
		
		private decimal _vrUnitarioPedagio;
		public virtual decimal VrUnitarioPedagio
		{
			get
			{
				return this._vrUnitarioPedagio;
			}
			set
			{
				this._vrUnitarioPedagio = value;
			}
		}
		
		private decimal _vrUnitarioKM;
		public virtual decimal VrUnitarioKM
		{
			get
			{
				return this._vrUnitarioKM;
			}
			set
			{
				this._vrUnitarioKM = value;
			}
		}
		
		private int _qtdeLugares;
		public virtual int QtdeLugares
		{
			get
			{
				return this._qtdeLugares;
			}
			set
			{
				this._qtdeLugares = value;
			}
		}
		
		private IList<Passagem> _passagems = new List<Passagem>();
		public virtual IList<Passagem> Passagems
		{
			get
			{
				return this._passagems;
			}
		}
		
	}
}
#pragma warning restore 1591
